server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 90
    lease-expiration-duration-in-seconds: 120
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
